# Generated by Django 5.0.3 on 2025-08-06 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api_app', '0003_alter_teehole_handicap_alter_teehole_par'),
        ('course_review_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_review'),
        ),
    ]
