# Generated by Django 5.0.3 on 2025-08-13 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_review_app', '0002_alter_coursereview_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
