# Generated by Django 5.0.3 on 2025-08-05 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.BigIntegerField(unique=True)),
                ('club_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tee_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('course_rating', models.FloatField()),
                ('slope_rating', models.IntegerField()),
                ('bogey_rating', models.FloatField()),
                ('total_yards', models.IntegerField()),
                ('number_of_holes', models.IntegerField()),
                ('par_total', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tee_sets', to='course_api_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='TeeHole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.IntegerField()),
                ('par', models.IntegerField()),
                ('yardage', models.IntegerField()),
                ('handicap', models.IntegerField()),
                ('tee_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='course_api_app.teeset')),
            ],
        ),
    ]
