# Generated by Django 5.0.3 on 2025-08-05 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teehole',
            name='hole_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)]),
        ),
        migrations.AlterUniqueTogether(
            name='teehole',
            unique_together={('tee_set', 'hole_number')},
        ),
    ]
