# Generated by Django 5.0.3 on 2025-08-06 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api_app', '0002_alter_teehole_hole_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teehole',
            name='handicap',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='teehole',
            name='par',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
