# Generated by Django 5.0.3 on 2025-08-13 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api_app', '0003_alter_teehole_handicap_alter_teehole_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teehole',
            name='handicap',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='teeset',
            name='par_total',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
