# Generated by Django 5.0.3 on 2025-08-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api_app', '0004_alter_teehole_handicap_alter_teeset_par_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
