# Generated by Django 5.0.3 on 2025-08-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api_app', '0005_alter_course_address_alter_course_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='address',
            field=models.CharField(blank=True, default='No Data', max_length=255, null=True),
        ),
    ]
