# Generated by Django 5.0.3 on 2025-08-06 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_api_app', '0002_alter_teehole_hole_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_api_app.course')),
                ('tee_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_api_app.teeset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strokes', models.IntegerField(blank=True, null=True)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scorecard_app.scorecard')),
                ('tee_hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_api_app.teehole')),
            ],
        ),
    ]
