# Generated by Django 5.0.3 on 2025-08-06 20:43

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='date_played',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='strokes',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
