# Generated by Django 5.0.3 on 2025-08-14 20:34

import scorecard_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard_app', '0002_alter_scorecard_date_played_alter_scoreentry_strokes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='date_played',
            field=models.DateField(default=scorecard_app.models.get_current_date),
        ),
    ]
